In [54]:
from pyaaas.aaas import AaaS
from pyaaas.models.privacy_models import KAnonymity
from pyaaas.attribute_type import AttributeType
import pandas as pd

In [55]:
aaas = AaaS("http://35.228.153.53:8080/") # connecting to online service

In [56]:
data_df = pd.read_csv("../data/dummy-dataset-260219.csv", sep=";")

In [57]:
data_df

,Dummy_tag,ID,Navn,Alder,Sivilstatus,Barn,Innsatsgruppe,Innvandrerbakgrunn,Ledighetsstatus,Utdanning,Ytelse,Medisinsk forhold
0,dummy_data,PY827,Eirik,47,Ukjent,1,Situasjonsbestemt innsats,Togo,Delvis ledig,Høyere utd inntil 4 år,Tiltakspenger,Ingen
1,dummy_data,CX244,Ella,30,Gift,2,Varig tilpasset,Surinam,Ordinær tiltaksdeltaker,Grunnskole,Dagpenger,Ingen
2,dummy_data,ZE697,Solveig,37,Ukjent,1,Standard innsats,Malta,Delvis ledig,Grunnskole,Dagpenger,Ingen
3,dummy_data,AR215,Eirik,52,Ugift,1,Standard innsats,Norge,Andre arbeidssøkende,Høyere utd inntil 4 år,Uføretrygd,Ingen
4,dummy_data,CZ546,Heidi,37,Ukjent,3,Spesielt tilpasset,Surinam,Andre arbeidssøkende,Høyere utd over 4 år,Dagpenger,Ingen
5,dummy_data,XF859,Nora,30,Gift,2,Spesielt tilpasset,Malta,Andre arbeidssøkende,VGS,Uføretrygd,Ingen
6,dummy_data,LN430,Sara,42,Enke,2,Situasjonsbestemt innsats,Norge,Andre arbeidssøkende,Høyere utd inntil 4 år,Tiltakspenger,Ingen
7,dummy_data,UX876,Johan,39,Enke,1,Varig tilpasset,Norge,Helt ledig,VGS,Tiltakspenger,Ingen
8,dummy_data,TO107,Tobias,37,Enke,2,Standard innsats,Norge,Delvis ledig,Grunnskole,Dagpenger,Ingen
9,dummy_data,OY439,Ella,42,Gift,2,Standard innsats,Malta,Helt ledig,Ukjent,Tiltakspenger,Ingen
10,dummy_data,VQ216,Arne,41,Enke,2,Standard innsats,Norge,Ordinær tiltaksdeltaker,Grunnskole,Sykepenger,Ingen
11,dummy_data,VI298,Ole,33,Enke,3,Varig tilpasset,Norge,Helt ledig,Høyere utd inntil 4 år,Dagpenger,Ingen
12,dummy_data,QE188,Kristine,42,Skilt,0,Standard innsats,Norge,Ordinær tiltaksdeltaker,VGS,Uføretrygd,Ingen
13,dummy_data,UL777,Stein,36,Skilt,2,Standard innsats,Norge,Helt ledig,VGS,Arbeidsavklaringspenger,Artrose
14,dummy_data,UB444,Anne,35,Ugift,3,Standard innsats,Norge,Andre arbeidssøkende,VGS,Dagpenger,Hjerteflimmer
15,dummy_data,AQ596,Tobias,51,Enke,1,Standard innsats,Neptun,Helt ledig,VGS,Tiltakspenger,Ingen
16,dummy_data,EG195,Ingrid,50,Skilt,1,Standard innsats,Norge,Ordinær tiltaksdeltaker,Grunnskole,Tiltakspenger,Ingen
17,dummy_data,TZ807,Eirik,49,Ukjent,1,Standard innsats,Jupiter,Ordinær tiltaksdeltaker,Høyere utd inntil 4 år,Tiltakspenger,Hjerteflimmer
18,dummy_data,ZE853,Tobias,40,Enke,1,Standard innsats,Togo,Helt ledig,Ukjent,Dagpenger,Ingen
19,dummy_data,AT459,Ole,42,Ukjent,1,Standard innsats,Norge,Ordinær tiltaksdeltaker,VGS,Dagpenger,Ingen
20,dummy_data,SD342,Arne,53,Skilt,3,Situasjonsbestemt innsats,Japan,Ordinær tiltaksdeltaker,VGS,Dagpenger,Ingen
21,dummy_data,GX164,Eirik,30,Gift,2,Standard innsats,Neptun,Helt ledig,VGS,Uføretrygd,Ingen
22,dummy_data,LR559,Andreas,44,Enke,1,Spesielt tilpasset,Norge,Ordinær tiltaksdeltaker,Høyere utd over 4 år,Dagpenger,Ingen
23,dummy_data,WU728,Arne,33,Ugift,3,Standard innsats,Surinam,Ordinær tiltaksdeltaker,Ukjent,Sykepenger,Artrose
24,dummy_data,RI100,Hans,56,Enke,2,Standard innsats,Norge,Helt ledig,VGS,Tiltakspenger,Ingen
25,dummy_data,RF333,Ingrid,41,Gift,2,Spesielt tilpasset,Togo,Delvis ledig,Høyere utd over 4 år,Tiltakspenger,Hjerteflimmer
26,dummy_data,ZT998,Sara,37,Gift,1,Standard innsats,Norge,Helt ledig,Høyere utd inntil 4 år,Dagpenger,Diabetes
27,dummy_data,CG525,Stine,54,Ukjent,4,Standard innsats,Togo,Ordinær tiltaksdeltaker,VGS,Uføretrygd,Ingen
28,dummy_data,IR748,Heidi,41,Skilt,0,Standard innsats,Norge,Delvis ledig,Høyere utd inntil 4 år,Arbeidsavklaringspenger,Ingen
29,dummy_data,PX220,Ella,33,Enke,1,Varig tilpasset,Norge,Andre arbeidssøkende,Høyere utd over 4 år,Dagpenger,Ingen
...,...,...,...,...,...,...,...,...,...,...,...,...
4970,dummy_data,LU989,Nora,54,Gift,-1,Varig tilpasset,Norge,Andre arbeidssøkende,VGS,Dagpenger,Ingen
4971,dummy_data,XM121,Eirik,38,Gift,1,Standard innsats,Norge,Helt ledig,VGS,Arbeidsavklaringspenger,Ingen
4972,dummy_data,NU610,Ole,41,Enke,0,Standard innsats,Norge,Delvis ledig,VGS,Sykepenger,Ingen
4973,dummy_data,MC377,Johan,51,Enke,2,Standard innsats,Malta,Ordinær tiltaksdeltaker,Ukjent,Dagpenger,Ingen
4974,dummy_data,JK262,Marie,44,Skilt,2,Standard innsats,Togo,Helt ledig,Høyere utd over 4 år,Tiltakspenger,Hjerteflimmer
4975,dummy_data,PL554,Stine,31,Skilt,3,Standard innsats,Norge,Ordinær tiltaksdeltaker,Høyere utd inntil 4 år,Dagpenger,Artrose
4976,dummy_data,QB899,Eirik,36,Skilt,2,Standard innsats,Norge,Ordinær tiltaksdeltaker,VGS,Dagpenger,Artrose
4977,dummy_data,DK920,Hans,47,Skilt,1,Standard innsats,Norge,Helt ledig,VGS,Dagpenger,Ingen
4978,dummy_data,GH133,Einar,43,Enke,3,Situasjonsbestemt innsats,Norge,Helt ledig,Høyere utd inntil 4 år,Tiltakspenger,Ingen
4979,dummy_data,IJ786,Sara,47,Skilt,2,Situasjonsbestemt innsats,Norge,Helt ledig,Høyere utd inntil 4 år,Dagpenger,Diabetes
4980,dummy_data,YT416,Ingrid,42,Skilt,3,Situasjonsbestemt innsats,Norge,Ordinær tiltaksdeltaker,VGS,Tiltakspenger,Artrose
4981,dummy_data,ZH563,Marie,44,Ukjent,1,Situasjonsbestemt innsats,Neptun,Delvis ledig,Høyere utd over 4 år,Sykepenger,Ingen
4982,dummy_data,VA886,Hans,36,Gift,2,Standard innsats,Malta,Delvis ledig,Høyere utd inntil 4 år,Arbeidsavklaringspenger,Ingen
4983,dummy_data,HI598,Stein,54,Gift,1,Standard innsats,Neptun,Ordinær tiltaksdeltaker,VGS,Uføretrygd,Ingen
4984,dummy_data,ZX393,Solveig,40,Ukjent,4,Standard innsats,Norge,Helt ledig,Høyere utd inntil 4 år,Sykepenger,Artrose
4985,dummy_data,BM172,Tobias,42,Ugift,3,Standard innsats,Malta,Helt ledig,Høyere utd inntil 4 år,Arbeidsavklaringspenger,Ingen
4986,dummy_data,AT781,Ole,36,Ukjent,5,Standard innsats,Norge,Ordinær tiltaksdeltaker,Høyere utd inntil 4 år,Uføretrygd,Ingen
4987,dummy_data,BG733,Einar,44,Skilt,2,Standard innsats,Norge,Andre arbeidssøkende,VGS,Dagpenger,Ingen
4988,dummy_data,UM395,Stein,39,Enke,3,Spesielt tilpasset,Malta,Ordinær tiltaksdeltaker,VGS,Tiltakspenger,Ingen
4989,dummy_data,BK468,Arne,39,Ukjent,0,Standard innsats,Norge,Ordinær tiltaksdeltaker,Høyere utd over 4 år,Tiltakspenger,Hjerteflimmer
4990,dummy_data,LT502,Arne,33,Gift,3,Varig tilpasset,Malta,Ordinær tiltaksdeltaker,Høyere utd over 4 år,Arbeidsavklaringspenger,Ingen
4991,dummy_data,KV910,Stein,33,Enke,2,Standard innsats,Norge,Ordinær tiltaksdeltaker,VGS,Dagpenger,Ingen
4992,dummy_data,CS971,Ole,45,Gift,2,Standard innsats,Surinam,Helt ledig,Høyere utd over 4 år,Sykepenger,Ingen
4993,dummy_data,UP209,Einar,46,Ugift,2,Standard innsats,Norge,Andre arbeidssøkende,Høyere utd inntil 4 år,Tiltakspenger,Diabetes
4994,dummy_data,BH352,Kristian,42,Ukjent,1,Varig tilpasset,Norge,Helt ledig,Ukjent,Dagpenger,Ingen
4995,dummy_data,AI829,Andreas,38,Enke,2,Standard innsats,Norge,Andre arbeidssøkende,VGS,Dagpenger,Diabetes
4996,dummy_data,MN372,Nora,42,Skilt,1,Spesielt tilpasset,Norge,Helt ledig,Høyere utd inntil 4 år,Arbeidsavklaringspenger,Ingen
4997,dummy_data,IR378,Ingrid,39,Skilt,3,Standard innsats,Norge,Ordinær tiltaksdeltaker,VGS,Dagpenger,Ingen
4998,dummy_data,SI932,Einar,36,Gift,1,Spesielt tilpasset,Surinam,Ordinær tiltaksdeltaker,VGS,Dagpenger,Ingen
4999,dummy_data,NE378,Ella,36,Skilt,3,Spesielt tilpasset,Norge,Helt ledig,VGS,Tiltakspenger,Ingen

In [58]:
aaas.set_data(data_df)

In [59]:
headers = data_df.columns.values.tolist()
headers

['Dummy_tag',
 'ID',
 'Navn',
 'Alder',
 'Sivilstatus',
 'Barn',
 'Innsatsgruppe',
 'Innvandrerbakgrunn',
 'Ledighetsstatus',
 'Utdanning',
 'Ytelse',
 'Medisinsk forhold']

In [60]:
attribute_types = {
 'Dummy_tag': AttributeType.INSENSITIVE,
 'ID': AttributeType.IDENTIFYING,
 'Navn': AttributeType.IDENTIFYING,
 'Alder': AttributeType.INSENSITIVE,
 'Sivilstatus': AttributeType.INSENSITIVE,
 'Barn': AttributeType.INSENSITIVE,
 'Innsatsgruppe': AttributeType.INSENSITIVE,
 'Innvandrerbakgrunn': AttributeType.QUASIIDENTIFYING,
 'Ledighetsstatus': AttributeType.QUASIIDENTIFYING,
 'Utdanning': AttributeType.INSENSITIVE,
 'Ytelse': AttributeType.QUASIIDENTIFYING,
 'Medisinsk forhold': AttributeType.IDENTIFYING
}

### Set Generalization Hierarchies
Note that if the hierarchy does not have a header row in the csv file, please set header=None in read_csv() or the first row will be interpreted as a header and ARXaaS will throw an exception for the missing hierarchy data.

In [61]:
ytelse_hierarchy = pd.read_csv("../hierarchies/Ytelse_hierarchy.csv", sep=";", header=None)
innsatsgruppe_hierarchy = pd.read_csv("../hierarchies/innsatsgruppe_hierarchy.csv", sep=";", header=None)
innvandrerbakgrunn_hierarchy = pd.read_csv("../hierarchies/innvandrerbakgrunn_hierarchy.csv", sep=";", header=None)
ledighetsstatus_hierarchy = pd.read_csv("../hierarchies/ledighetsstatus_hierarchy.csv", sep=";", header=None)

In [62]:
aaas.set_hierarchy('Ytelse', ytelse_hierarchy)
aaas.set_hierarchy("Innsatsgruppe", innsatsgruppe_hierarchy)
aaas.set_hierarchy("Innvandrerbakgrunn", innvandrerbakgrunn_hierarchy)
aaas.set_hierarchy("Ledighetsstatus", ledighetsstatus_hierarchy)

In [63]:
ledighetsstatus_hierarchy

                         0             1  2
0     Andre arbeidssøkende  Delvis ledig  *
1             Delvis ledig  Delvis ledig  *
2               Helt ledig         ledig  *
3  Ordinær tiltaksdeltaker         ledig  *

### Set Privacy Models

In [64]:
kanon = KAnonymity(4)

In [65]:
aaas.set_model(kanon)

In [66]:
aaas.set_attribute_type(attribute_types)

### Run anonymization

In [67]:
result = aaas.anonymize()

In [68]:
result

In [69]:
result.get_result_dataframe()

,Dummy_tag,ID,Navn,Alder,Sivilstatus,Barn,Innsatsgruppe,Innvandrerbakgrunn,Ledighetsstatus,Utdanning,Ytelse,Medisinsk forhold
0,dummy_data,*,*,47,Ukjent,1,Spesielt tilpasset,Togo,Delvis ledig,Høyere utd inntil 4 år,Tiltakspenger,*
1,dummy_data,*,*,30,Gift,2,Varig tilpasset,Surinam,ledig,Grunnskole,Dagpenger,*
2,dummy_data,*,*,37,Ukjent,1,Varig tilpasset,Malta,Delvis ledig,Grunnskole,Dagpenger,*
3,dummy_data,*,*,52,Ugift,1,Varig tilpasset,Norge,Delvis ledig,Høyere utd inntil 4 år,Uføretrygd,*
4,dummy_data,*,*,37,Ukjent,3,Spesielt tilpasset,Surinam,Delvis ledig,Høyere utd over 4 år,Dagpenger,*
5,dummy_data,*,*,30,Gift,2,Spesielt tilpasset,Malta,Delvis ledig,VGS,Uføretrygd,*
6,dummy_data,*,*,42,Enke,2,Spesielt tilpasset,Norge,Delvis ledig,Høyere utd inntil 4 år,Tiltakspenger,*
7,dummy_data,*,*,39,Enke,1,Varig tilpasset,Norge,ledig,VGS,Tiltakspenger,*
8,dummy_data,*,*,37,Enke,2,Varig tilpasset,Norge,Delvis ledig,Grunnskole,Dagpenger,*
9,dummy_data,*,*,42,Gift,2,Varig tilpasset,Malta,ledig,Ukjent,Tiltakspenger,*
10,dummy_data,*,*,41,Enke,2,Varig tilpasset,Norge,ledig,Grunnskole,Sykepenger,*
11,dummy_data,*,*,33,Enke,3,Varig tilpasset,Norge,ledig,Høyere utd inntil 4 år,Dagpenger,*
12,dummy_data,*,*,42,Skilt,0,Varig tilpasset,Norge,ledig,VGS,Uføretrygd,*
13,dummy_data,*,*,36,Skilt,2,Varig tilpasset,Norge,ledig,VGS,Arbeidsavklaringspenger,*
14,dummy_data,*,*,35,Ugift,3,Varig tilpasset,Norge,Delvis ledig,VGS,Dagpenger,*
15,dummy_data,*,*,51,Enke,1,Varig tilpasset,Neptun,ledig,VGS,Tiltakspenger,*
16,dummy_data,*,*,50,Skilt,1,Varig tilpasset,Norge,ledig,Grunnskole,Tiltakspenger,*
17,dummy_data,*,*,49,Ukjent,1,Varig tilpasset,Jupiter,ledig,Høyere utd inntil 4 år,Tiltakspenger,*
18,dummy_data,*,*,40,Enke,1,Varig tilpasset,Togo,ledig,Ukjent,Dagpenger,*
19,dummy_data,*,*,42,Ukjent,1,Varig tilpasset,Norge,ledig,VGS,Dagpenger,*
20,dummy_data,*,*,53,Skilt,3,Spesielt tilpasset,Japan,ledig,VGS,Dagpenger,*
21,dummy_data,*,*,30,Gift,2,Varig tilpasset,Neptun,ledig,VGS,Uføretrygd,*
22,dummy_data,*,*,44,Enke,1,Spesielt tilpasset,Norge,ledig,Høyere utd over 4 år,Dagpenger,*
23,dummy_data,*,*,33,Ugift,3,Varig tilpasset,Surinam,ledig,Ukjent,Sykepenger,*
24,dummy_data,*,*,56,Enke,2,Varig tilpasset,Norge,ledig,VGS,Tiltakspenger,*
25,dummy_data,*,*,41,Gift,2,Spesielt tilpasset,Togo,Delvis ledig,Høyere utd over 4 år,Tiltakspenger,*
26,dummy_data,*,*,37,Gift,1,Varig tilpasset,Norge,ledig,Høyere utd inntil 4 år,Dagpenger,*
27,dummy_data,*,*,54,Ukjent,4,Varig tilpasset,Togo,ledig,VGS,Uføretrygd,*
28,dummy_data,*,*,41,Skilt,0,Varig tilpasset,Norge,Delvis ledig,Høyere utd inntil 4 år,Arbeidsavklaringspenger,*
29,dummy_data,*,*,33,Enke,1,Varig tilpasset,Norge,Delvis ledig,Høyere utd over 4 år,Dagpenger,*
...,...,...,...,...,...,...,...,...,...,...,...,...
4970,dummy_data,*,*,54,Gift,-1,Varig tilpasset,Norge,Delvis ledig,VGS,Dagpenger,*
4971,dummy_data,*,*,38,Gift,1,Varig tilpasset,Norge,ledig,VGS,Arbeidsavklaringspenger,*
4972,dummy_data,*,*,41,Enke,0,Varig tilpasset,Norge,Delvis ledig,VGS,Sykepenger,*
4973,dummy_data,*,*,51,Enke,2,Varig tilpasset,Malta,ledig,Ukjent,Dagpenger,*
4974,dummy_data,*,*,44,Skilt,2,Varig tilpasset,Togo,ledig,Høyere utd over 4 år,Tiltakspenger,*
4975,dummy_data,*,*,31,Skilt,3,Varig tilpasset,Norge,ledig,Høyere utd inntil 4 år,Dagpenger,*
4976,dummy_data,*,*,36,Skilt,2,Varig tilpasset,Norge,ledig,VGS,Dagpenger,*
4977,dummy_data,*,*,47,Skilt,1,Varig tilpasset,Norge,ledig,VGS,Dagpenger,*
4978,dummy_data,*,*,43,Enke,3,Spesielt tilpasset,Norge,ledig,Høyere utd inntil 4 år,Tiltakspenger,*
4979,dummy_data,*,*,47,Skilt,2,Spesielt tilpasset,Norge,ledig,Høyere utd inntil 4 år,Dagpenger,*
4980,dummy_data,*,*,42,Skilt,3,Spesielt tilpasset,Norge,ledig,VGS,Tiltakspenger,*
4981,dummy_data,*,*,44,Ukjent,1,Spesielt tilpasset,Neptun,Delvis ledig,Høyere utd over 4 år,Sykepenger,*
4982,dummy_data,*,*,36,Gift,2,Varig tilpasset,Malta,Delvis ledig,Høyere utd inntil 4 år,Arbeidsavklaringspenger,*
4983,dummy_data,*,*,54,Gift,1,Varig tilpasset,Neptun,ledig,VGS,Uføretrygd,*
4984,dummy_data,*,*,40,Ukjent,4,Varig tilpasset,Norge,ledig,Høyere utd inntil 4 år,Sykepenger,*
4985,dummy_data,*,*,42,Ugift,3,Varig tilpasset,Malta,ledig,Høyere utd inntil 4 år,Arbeidsavklaringspenger,*
4986,dummy_data,*,*,36,Ukjent,5,Varig tilpasset,Norge,ledig,Høyere utd inntil 4 år,Uføretrygd,*
4987,dummy_data,*,*,44,Skilt,2,Varig tilpasset,Norge,Delvis ledig,VGS,Dagpenger,*
4988,dummy_data,*,*,39,Enke,3,Spesielt tilpasset,Malta,ledig,VGS,Tiltakspenger,*
4989,dummy_data,*,*,39,Ukjent,0,Varig tilpasset,Norge,ledig,Høyere utd over 4 år,Tiltakspenger,*
4990,dummy_data,*,*,33,Gift,3,Varig tilpasset,Malta,ledig,Høyere utd over 4 år,Arbeidsavklaringspenger,*
4991,dummy_data,*,*,33,Enke,2,Varig tilpasset,Norge,ledig,VGS,Dagpenger,*
4992,dummy_data,*,*,45,Gift,2,Varig tilpasset,Surinam,ledig,Høyere utd over 4 år,Sykepenger,*
4993,dummy_data,*,*,46,Ugift,2,Varig tilpasset,Norge,Delvis ledig,Høyere utd inntil 4 år,Tiltakspenger,*
4994,dummy_data,*,*,42,Ukjent,1,Varig tilpasset,Norge,ledig,Ukjent,Dagpenger,*
4995,dummy_data,*,*,38,Enke,2,Varig tilpasset,Norge,Delvis ledig,VGS,Dagpenger,*
4996,dummy_data,*,*,42,Skilt,1,Spesielt tilpasset,Norge,ledig,Høyere utd inntil 4 år,Arbeidsavklaringspenger,*
4997,dummy_data,*,*,39,Skilt,3,Varig tilpasset,Norge,ledig,VGS,Dagpenger,*
4998,dummy_data,*,*,36,Gift,1,Spesielt tilpasset,Surinam,ledig,VGS,Dagpenger,*
4999,dummy_data,*,*,36,Skilt,3,Spesielt tilpasset,Norge,ledig,VGS,Tiltakspenger,*

In [70]:
result.get_metrics_before()

                                                                          value
metric
measure_value                                                               [%]
records_affected_by_highest_risk                                           0.08
sample_uniques                                                              0.0
estimated_prosecutor_risk                                                  50.0
population_model                                                         DANKAR
records_affected_by_lowest_risk                                           40.98
estimated_marketer_risk                                                    3.58
highest_prosecutor_risk                                                    50.0
estimated_journalist_risk                                                  50.0
lowest_risk                                                 0.27472527472527475
average_prosecutor_risk                                                    3.58
population_uniques                                                          0.0
quasi_identifiers                 [Innvandrerbakgrunn, Ytelse, Ledighetsstatus]

In [71]:
result.get_metrics_after()

                                                                          value
metric
measure_value                                                               [%]
records_affected_by_highest_risk                                            0.3
sample_uniques                                                              0.0
estimated_prosecutor_risk                                                  20.0
population_model                                                         DANKAR
records_affected_by_lowest_risk                               57.55999999999999
estimated_marketer_risk                                                    1.82
highest_prosecutor_risk                                                    20.0
estimated_journalist_risk                                                  20.0
lowest_risk                                                  0.1594896331738437
average_prosecutor_risk                                                    1.82
population_uniques                                                          0.0
quasi_identifiers                 [Innvandrerbakgrunn, Ytelse, Ledighetsstatus]